### PR TITLE
What is this for?

### PR DESCRIPTION
**Pull request by AsaAyers**
https://www.npmjs.com/package/linter-clay-coffeelint

Why is this fork being published to npm under a new name? It seems to just be a significantly outdated version of the original.

I'm issuing a PR since you don't have issues turned on.

### CODE REVIEW

**Comment by Zolmeister** [comment]
Sorry for the confusion, I'll update the Readme
This fork of the linter comes with out company style-guide (https://github.com/claydotio/coffeescript-style-guide) embedded, to ensure consistency accross projects without copy-and-pasting the same coffeelint.json (and manually updating) all the time

**Comment by AsaAyers** [comment]
Please don't do that. Please just use coffeelint.json in your projects.

When it comes to linting, configuring your editor is always the wrong solution. Your solution here only works as long as 100% of your developers use Atom and continue to use Atom forever. If you configure your projects properly then it doesn't matter if someone decides to use vim, or emacs or even if they run coffeelint from the command line. You will get consistent results.

Don't you lint as part of continuous integration or tests? If you're only configuring your editor by using a fork of a plugin then you have to maintain that configuration in two places. And if it's in version control that means you still need a `coffeelint.json`, so this plugin doesn't really do anything.

**Comment by Zolmeister** [comment]
Let me expand. We have our style guide config as a dependency in our projects (e.g: https://github.com/Zorium/zorium-seed/blob/master/Gulpfile.coffee#L14) to use with gulp-coffeelint. The editor plugin is simply for convenience.

**Comment by AsaAyers** [comment]
So what I'm hearing is that it would help to have something like ESLint's ability to extend external configurations. http://eslint.org/docs/user-guide/configuring search `Extending Configuration Files`

No one has opened an issue for that in CoffeeLint yet.

**Comment by Zolmeister** [comment]
Good call.

**Pull request closed without merging**
